name: Main

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Merge and release latest changes into the SVN repo
        env:
          COMMIT_MSG:  ${{ github.event.head_commit.message }}
          SVN_SECRET: ${{ secrets.WP_SVN_SECRET }}
          TAG: ${{ github.ref_name }}
        run: |
          cd ..
          mkdir pp-wp-svn
          svn co https://plugins.svn.wordpress.org/printapp pp-wp-svn
          cp -r print-app-wordpress/. pp-wp-svn/trunk/
          cd pp-wp-svn
          VERSION="$(echo $TAG | cut -c2-)"
          svn cp trunk/ tags/$VERSION
          svn ci -m "$COMMIT_MSG" --username printapp --password $SVN_SECRET
      
      - name: Commit the version updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
      # - name: Just checking
      #   run: echo 
      # - name: Checkout
      # - name: Create asset
      #   run: cd .. && zip testBump.zip testBump/* -r && cd testBump/
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     body_path: "CHANGELOG.txt"
      #     name: "Print.App - PrestaShop 1.7.x - ${{ github.ref_name }}"
      #     files: "../testBump.zip"
